baseURL: "https://yuminghuo.github.io"
languageCode: en-us
title: Yuming Huo
theme: PaperMod

menu:
  main:
    # - identifier: about
    #   name: About me
    #   url: /about/
    #   weight: 10
    # - identifier: project
    #   name: My project
    #   url: /project/
    #   weight: 20
    # - identifier: resume
    #   name: Resume
    #   url: /cv.pdf/
    #   weight: 30
    - identifier: secret
      name: My secrets
      # url: /posts/
      url: /secret/
      weight: 40
    - identifier: search
      name: Search
      url: /search/
      weight: 50

params:
    defaultTheme: dark
    ShowShareButtons: false #每个帖子下添加分享按钮
    ShowReadingTime: true #显示帖子阅读时间
    author: ["Yuming"]
    ShowBreadCrumbs: true
    ShowPostNavLinks: true #帖子下方的其他帖子建议

    profileMode:
        enabled: true
        title: "<About Yuming>" # optional default will be site title
        subtitle: "Yuming Huo"
        imageUrl: "img/title.JPG" # optional
        imageTitle: "Yuming Huo" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: About me
              url: "about"
            - name: My project
              url: "project"
            - name: Resume
              url: "cv.pdf"

    socialIcons: # optional
        - name: "Github"
          url: "https://github.com/YumingHuo"
        - name: "email"
          url: "mailto:hym811@outlook.com"
        - name: "Discord"
          url: "https://discordapp.com/users/huoh."